name: Core
version: 5.0
author: Prestige_Pvp
main: com.customhcf.base.BasePlugin
commands:
  core:
  warp:
      description: Turns the server to Donor only mode.
      aliases: [gw, globalwarp]
  toggledonoronly:
    description: Turns the server to Donor only mode.
    aliases: [donoronly, donormode]
  history:
  request:
  clearlagg:
    aliases: ["cl", "laggclear", "clearlag", "clag"]
  announcement:
    aliases: ["announce", "ann"]
  note:
  copyinv:
  amivis:
    aliases: ["amivanish", "amivanished", "?invis", "?v", "?vis", "invis?", "vis?", "v?"]
    description: Command used to check if visible.
  autorestart:
    description: Handle server restarts safely.
  back:
    description: Teleport to last known location.
  biome:
    description: Check the biome a player is in.
  broadcast:
    aliases: [bc]
    description: Broadcast a server message.
  clearchat:
    aliases: [cc]
    description: Clear the chat history.
  clearinv:
    aliases: [ci, clear, cpinv]
    description: Clears a player inventory.
  enchant:
    description: Enchant an item.
  entities:
    description: Check the entities in a world.
  fly:
    description: Toggle flight for a player.
  feed:
    description: Feed a player.
  freeze:
    description: Command used to freeze players.
    aliases: [ss]
  gamemode:
    aliases: [gm]
    description: Update a players gamemode.
  give:
    description: Give an item to a player.
  hat:
    description: Wear something as a hat.
  heal:
    description: Heal a player.
  id:
    description: Check the id of an item.
  ignore:
    description: Ignore a player from messaging you
  invsee:
    aliases: [inventory, inventorysee, inv]
    description: View a players inventory.
  item:
    aliases: [i]
    description: Spawn an item.
  iphistory:
    description: Check the history an IP address or player.
  kill:
    aliases: [suicide, slay]
    description: Kill a player.
  kit:
    description: Command to apply or use kits.
  message:
    aliases: [m, msg, tell, whisper, w]
    description: Messsage an online player.
  socialspy:
    aliases: [ms, msgspy, pmspy, whisperspy, privatemessagespy, tellspy]
    description: Command used to spy on pm's of players.
  more:
    description: Give yourself more of an item.
  mutechat:
    aliases: [mc, rc, restrictchat, disablechat]
    description: Restricts the use of global chat.
  namehistory:
    description: Check the name histories of a player.
  near:
    description: Check nearby entities to a player.
  ping:
    aliases: [p]
    description: Checks the ping of a player.
  playtime:
    aliases: [pt]
    description: Track a players total playtime of the map.
  playertime:
    aliases: [ptime]
    description: Shows your player time.
  position:
    description: Checks the position of a player.
  removeentity:
    aliases: [reme, rem]
    description: Remove entities from the server.
  rename:
    description: Command used to rename items.
  repair:
    aliases: [fix]
    description: Allows the repairing of tools.
  report:
    description: Report
  donate:
    aliases: [buy]
    description: Gets the donation link.
  reply:
    aliases: [r]
    description: Reply to a player message.
  rules:
    description: Shows the server rules.
  screenshare:
  seen:
    description: Checks when a player was last seen.
  setmaxplayers:
    description: Set the maximum player count.
  skull:
    description: Spawn the skull of a player.
  slowchat:
    aliases: [slow]
    description: Sets a delay between chat messages.
  sounds:
    aliases: [pmsounds, togglepmsounds, messagingsounds]
    description: Toggles messaging sounds
  speed:
    description: Set your walk or fly speed.
  stoplag:
  createworld:
  sudo:
    description: Force another player to run a command.
  teleport:
    aliases: [tp]
    description: Teleport to a player or location.
  teleportall:
    aliases: [tpall]
    description: Teleport all online players somewhere.
  teleporthere:
    aliases: [tphere]
    description: Teleport a player to self.
  togglechat:
    aliases: [tgc, toggleglobalchat]
    description: Toggles global chat visibility on or off.
  togglestaffchat:
    aliases: [tsc, togglesc]
    description: Toggles staff chat visibility on or off.
  togglemessages:
    aliases: [togglepm, toggleprivatemessages]
    description: Disable private messages.
  top:
    description: Teleport to highest spot of world
  unfreeze:
    description: Un-freezes' a player.
  uptime:
    description: Check how long a server has been up for.
  whois:
    description: Check information about a player.
  world:
    description: Change your current world.